# Generated by Django 5.0.6 on 2024-06-09 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='education_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user_en',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Medicine.userprofile'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user_ru',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Medicine.userprofile'),
        ),
    ]
