# Generated by Django 5.0.6 on 2024-06-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine', '0002_doctor_education_en_doctor_education_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
